name: Auto Deploy to WWW
on:
  push:
    branches:
      - main
    paths:
      - xmrig-remover.sh
  workflow_dispatch:

jobs:
  build:
    name: Deploy to WWW
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy xmrig-remover to WWW
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      run: |
        mkdir ~/.ssh
        echo "$SSH_DEPLOY_KEY" >~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        cd /tmp/
        git clone -b gh-pages --single-branch git@github.com:hackerschoice/hackerschoice.github.io.git
        cd hackerschoice.github.io
        cmp -s ../xmrig-remover.sh xmrig || { cat ../xmrig-remover.sh >xmrig; is_updated=1; }

        [ -n $is_updated ] && {
          git config --local user.name "GitHub Action"
          git config --local user.email "root@proton.thc.org"
          git add xmrig && git commit -m "xmrig-remover" && git push
        }
